### ISSUE TITLE
Unspecified directory for session-cookies

### ISSUE THREAD

**Issue by dwduback** [zvodd/Youtube-Watch-History-Scraper#1]
Under the section get-session-cookies I have the cookies in the .json file but I am unclear as to what directory that .json file should be in...

**Comment by rangira** [comment]
Hi I am very new to using an open source project in Python and it would be really helpful if anyone could help me. So I installed the dependencies using  "sudo pip install scrapy lxml sqlalchemy" and I copied the cookies on the clipboard as well. But where should I actually create the file "youtube_cookies.json". The description says "this directory". But I havent cloned anything and I am not sure to which directory should I be saving the json file to.

**Comment by zvodd** [comment]
Sorry I, completely missed this.
The `youtube_cookies.json` file will be taken from the `current directory` of the shell when executed, and that should be the same DIR as `scrapy.cfg`.

for example
````
git clone http://$(THE_REPO_URL) "Youtube-Watch-History-Scraper"
cd ./Youtube-Watch-History-Scraper # The same directory that the repo would've been cloned into
vim youtube_cookies.json  # add cookie data
scrapy crawl yth_spider
````
