### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by AB1908** [zvodd/Youtube-Watch-History-Scraper#5]
Although I've made changes and I'm maintaining a separate fork as well, I can't license my code unless the original repo has a license first. Kindly add a license or describe the rationale if you don't wish to add one.

**Comment by zvodd** [comment]
Done.

**Comment by AB1908** [comment]
Thank you

**Comment by AB1908** [comment]
You also might want to revert the readme. I accidentally included that commit when making a PR
